LMS API Integration
ubco-db/helpme pull request #186
Opened 2024-11-15 21:42 UTC by bhunt02

# Description

Initialization of an adapter pattern for LMS integrations into HelpMe for the purposes of:
1. Reading data for students to verify student status in the course
2. Reading data for assignments to potentially feed directly into the chatbot's knowledge base

Closes #182 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This change requires a database query to update old data on production. This query is below:

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any work that this PR is dependent on has been merged into the main branch
- [ ] Any UI changes have been checked to work on desktop, tablet, and mobile

2025-01-03 23:11 UTC, AdamFipke commented on packages/server/test/lmsIntegration.integration.ts
> +  });
> "Did you write tests for your feature?"

> "Yeah I wrote tests"

> The tests:

Kidding I read the PR description and yeah I agree we probably don't need many integration tests for this. Though, it may be a good idea to add some really simple integration tests for the new endpoints that are in the organization controller (though if it's hard to really make tests for these endpoints without mocking a bunch of stuff, maybe just some simple tests like "does it return 403 if the user is not an admin" or "does it return 401 if the user is not logged in")

2025-01-03 23:32 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +              {lmsIntegrations.length == 0 ? (
So when I first go to this page, I get "TypeError: Cannot read properties of undefined (reading 'length')"
I guess there are multiple ways to fix this, but I suppose the quickest one is to change the endpoint to make sure it's returning an empty array

2025-01-03 23:35 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +  }, [organizationId])
might want to add an error check, something like

```
await API.organizations.getIntegrations(organizationId)
      .then((response) => {
        setLmsIntegrations(response)
      })
      .catch((error) => {
        const errorMessage = getErrorMessage(error)
        message.error(errorMessage)
      })
```

2025-01-03 23:35 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +    setLmsIntegration(response)
same goes for this

2025-01-03 23:54 UTC, AdamFipke commented
okay so I guess it's a little hard for me to manually test the things, so I'll just kinda look over the code

2025-01-04 00:06 UTC, AdamFipke commented on packages/frontend/app/api/index.ts
> +    if (res == '') return undefined as T
may I ask why this change was made? Like was there a case with an endpoint that needed to return undefined but instead was giving an empty string?

Also I am a little bit concerned that there may be some pieces of frontend that assume that the response is an empty string and not undefined

2025-01-04 00:13 UTC, bhunt02 commented on packages/frontend/app/api/index.ts
> +    if (res == '') return undefined as T
cannot exactly remember? but i believe it was because there was strange behavior where 'undefined' responses were being returned as empty strings rather than undefined, and I don't believe this would have impacted other parts of the frontend but if you have an alternative/would like to check i'd make changes as needed

2025-01-04 00:42 UTC, AdamFipke requested changes
okay yeah just a few small things (see comments). I don't really have a way of testing to make sure all the new things work, but I don't see much that would break existing stuff (and it won't be *critical* if this breaks) so that should be fine. 

Overall nice work, code looks pretty slick

2025-01-04 00:46 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +  }, [organizationId])
should be addressed in latest commit

2025-01-04 00:46 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +    setLmsIntegration(response)
should be addressed in latest commit

2025-01-04 00:46 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx
> +              {lmsIntegrations.length == 0 ? (
should be addressed in latest commit

2025-01-04 00:46 UTC, bhunt02 commented on packages/server/test/lmsIntegration.integration.ts
> +  });
should be addressed in latest commit

2025-01-04 00:51 UTC, AdamFipke commented on packages/frontend/app/api/index.ts
> +    if (res == '') return undefined as T
Hmm I see, I guess one thought is maybe why does the endpoint need to return undefined and could it instead return something else? Or maybe another thought is adding a new optional parameter to `req` called something like `turnEmptyResponseToUndefined`. It's not really an *ideal* solution but it's probably the best way to make it work without possibly accidentally introducing new bugs

2025-01-04 05:25 UTC, bhunt02 commented on packages/frontend/app/api/index.ts
> +    if (res == '') return undefined as T
reversed... i think maybe a review of the API requests to see if the behavior of expecting an empty string is ever utilized, but I altered my implementation by using the property of empty strings, undefined, null etc. all being 'falsy' in ECMA script to accommodate this

2025-01-04 21:29 UTC, AdamFipke approved these changes
sweet, looks good!

2025-01-09 19:35 UTC, patrickma6199 approved these changes
Looks good! I like how you followed the paradigm for the adapter as well.

2025-01-09 20:53 UTC, merged