Queue Chats
ubco-db/helpme pull request #189
Opened 2024-11-25 16:56 UTC by patrickma6199

# Description

This feature was mainly motivated by the use cases where staff and students wish to contact each other but cannot prior to joining the Zoom call or meeting. This could range from being able to communicate about technical issues to why one might be late to a meeting. Queue chats also enable minor issues such as assignment detail questions to be handled via the chat instead of a Zoom call or physical meetings adding to the means of resource retrieval for students.

In the queue page, the chatbot button has been removed and replaced with the queue chat (regardless of queue location type). When a question is set to the "Helping" status, the queue chat automatically opens for both parties and closes automatically when the student's question is resolved. If two or more students are being helped at the same time, each student will get a private chat window with the staff member. When chats end, dated summary statistics and chat metadata are saved in the database for potential future investigation.

Closes #122 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [X] This change requires a database query to update old data on production. This is easily handled with included migrations.

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any work that this PR is dependent on has been merged into the main branch
- [ ] Any UI changes have been checked to work on desktop, tablet, and mobile

2025-01-04 21:39 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QueueQuestions.tsx
> +import { DeliveredProcedureOutlined } from '@ant-design/icons'
unused import

2025-01-04 21:47 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/layout.tsx
> +        ) : (
I really think the chatbot should still be visible inside the queue page since the usecase is "while you're waiting, you can use the chatbot without needing to switch pages" and I've also seen a few of my students use it here. 

It would only probably be fine to hide the chatbot while the student is *currently being helped* (though still not ideal, since maybe the student asks the chatbot something while waiting and wanted to bring it up during discussion with TA. I would say only hide the chatbot unless it's really hard to make the UI work with it

2025-01-04 21:50 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +      setIsOpen(true)
I think having it auto-open is a good idea, just don't have it auto-open for TAs on mobile since this chat modal can take up a big part of the screen.

2025-01-04 21:54 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +const QueueChat: React.FC<QueueChatProps> = ({
![image](https://github.com/user-attachments/assets/1a080897-a9c3-4eb1-8c8f-5d30e06c5cda)

I noticed that when you're helping multiple students on mobile it looks a little cutoff.

I guess you would need to maybe do a flex-row-wrap for the buttons. And then for the chat itself, you would need to restrict the user so that only 1 chat is open at a time on mobile.

Also to save a little bit of space with the button, maybe just have the first name of the student on mobile.

2025-01-04 21:57 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> -          <Card
also idk if there was just a git moment (like with merges or something) or what but it appears as though there's a lot of changed lines to the chatbot here and I was curious about what changes were needed here and why

2025-01-04 22:03 UTC, AdamFipke commented on packages/server/src/queue/queue-sse.service.ts
> +      async (queueId: number, studentId?: number) => {
was just curious on why the changes here were made? Since some of it looks like it may be leftover changes?

2025-01-04 22:07 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  studentId: number;
I saw this and got confused that this was like a university studentId. Maybe a better variable name could be studentUserId?

2025-01-04 22:10 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  staffId: number;
Also, are we sure we want to leave this nullable? Since I'm unsure if there's a case where it would be null unless a user was deleted, but in that case it would probably be wise to delete the queue chats associated with it (which it looks like you have already done)

And I suppose that also applies to queueId and studentId

2025-01-04 22:20 UTC, AdamFipke commented on packages/server/test/queueChats.integration.unfinished.ts
> +// PAT TODO: Figure out how to mock redis properly
yeah this is kinda a hard problem

maybe it would be worth looking into creating a "test" redis container that gets used for the tests? It might require some effort but at least in the future if we would ever add new features that utilized redis and want to write tests for it it would be a lot easier.

And yeah I know about the whole "we're not supposed to test other technologies and are just supposed to assume they work" thing but tbh I think that's kinda dumb since one of the main benefits to tests is regression testing (make changes and see if any tests fail) and being able to say update a framework or redis package or something and see what things broke right away is really nice and mocking the technology ruins that potential (and this was just things I thought about while I was trying to write integration tests for things that utilize the cron package).

2025-01-04 22:29 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +const QueueChat: React.FC<QueueChatProps> = ({
Also it's a little hard to notice in the screenshot, but the little outlines and numbers for the TaskMarkingSelector is showing on top of the queue chats. The old chatbot window did not have this problem.

It *might* be just as simple as increasing the z-index, but I imagine instead it will likely involve you needing to reorder the DOM so the queue chat is higher in the DOM

2025-01-04 22:31 UTC, AdamFipke requested changes
see comments

2025-01-09 21:07 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/layout.tsx
> +        ) : (
We discussed this in the meeting already before the break if you remember and we all agreed that this was too specific a use case to spend any time on. If a user really wants to use the chat bot while waiting in a queue, they can simply duplicate the tab and do so in a couple clicks.

2025-01-09 21:08 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +      setIsOpen(true)
Oh, I'll check this out, thanks for pointing it out.

2025-01-09 21:29 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> -          <Card
There was a redundant import and some other styling issues that I found (the bottom margin of the chat button was on top of the footer slightly). I hope I didn't mess anything up but when I was testing it before, nothing was wrong as far as I could tell. Could you maybe point out what's happening when you load up the chatbot locally for you?

2025-01-09 21:43 UTC, patrickma6199 commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  staffId: number;
I followed the paradigms present in almost all of our entities which all seem to have nullable columns where it might not actually be nullable in practice. I assumed there was some reason for this configuration so this is what I did as well for this entity. I could go back and change it but it doesn't introduce any vulnerabilities by being a nullable column just the same as the other nullable columns in other entities don't break the system either so it seems a bit redundant to spend time on by this point, unless we want to also change this for all of our other entities.

2025-01-09 21:46 UTC, patrickma6199 commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  studentId: number;
I'm not sure if this is necessary as I would have to delete the old migration and regenerate a new one. I think it might be easier to simply add a comment here for clarity. I feel like intuitively, after seeing the staffId attribute, it should be fairly clear that both user ids are foreign keys to the user table.

2025-01-09 22:05 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/layout.tsx
> +        ) : (
I think maybe we should have another discussion about this then, since I don't recall that being the outcome of that discussion. 

Also, some students will never see any part of the system outside of the queue page (for example, they click on a queue invite and get sent to the queue page, and then they see that there's a course chatbot that they can use that might be able to just answer their question right away. I can also see this as a very common use case if profs share a queue invite to their students).

2025-01-09 22:21 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  staffId: number;
It's just a maintenance/future-proofing thing so that future developers don't write a bad SQL query that leaves some of those fields null and causes the system to break because we were lacking nullish checks. It's a small thing

2025-01-09 22:37 UTC, patrickma6199 commented on packages/server/src/queue/queue-sse.service.ts
> +      async (queueId: number, studentId?: number) => {
Yea, i migrated the queue chat sse into its own service but since it was originally in this file, I left some changes there. I'll clean it up since you're right, nothing there really needs to change.

2025-01-09 23:15 UTC, patrickma6199 commented on packages/server/src/queueChats/queue-chats.entity.ts
> +  staffId: number;
Yea, but maybe we should add a general maintenance issue to change this for all entities because it is in a lot of entities that didn't need it.

2025-01-09 23:16 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/layout.tsx
> +        ) : (
Yea, we can discuss it tomorrow with the team since we're meeting anyways!

2025-01-11 00:08 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +            ? `${queueChatData!.student.firstName} ${queueChatData!.student.lastName}`
oh I didn't notice this before but I should probably mention that not all of our users have lastNames (some have null, somehow (I think it can happen after login with google)). You may have already handled this somewhere else in the code but I thought I would mention this just in case

2025-01-11 00:22 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TaskMarkingSelector.tsx
> +        zIndex: 0,
huh I thought this would break the green rotating thing behind the task but it actually seems fine

2025-01-14 20:32 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +            ? `${queueChatData!.student.firstName} ${queueChatData!.student.lastName}`
Oh, I wasn't aware. If it is sent as null in the response, I can easily fix that but I will test for this with a sample user.

2025-01-28 20:47 UTC, bhunt02 reviewed
can't say much, getting consistent 404's from redis even after running `yarn install`, I can try to give a better review later but I've left a few suggestions/changes nonetheless

2025-01-28 20:47 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +  }
visual issue on desktop:
![image](https://github.com/user-attachments/assets/e55224b8-9670-4230-aa99-25201f40bbe8)

2025-01-28 20:47 UTC, bhunt02 commented on packages/server/src/question/question.service.ts
> +      throw new HttpException(
Also, why are these all 404s?

2025-01-28 20:47 UTC, bhunt02 commented on packages/server/src/question/question.service.ts
> +    const isFirstHelped = isBecomingHelped && question.firstHelpedAt;
```suggestion
    const isFirstHelped = isBecomingHelped && !question.firstHelpedAt;
```

2025-01-28 20:47 UTC, bhunt02 commented on packages/server/src/queueChats/queue-chats.service.ts
> +    await this.redis.del(`${ChatMessageRedisKey}:${queueId}:${student.id}`);
is there a reason this is present twice?

2025-01-28 21:33 UTC, patrickma6199 commented on packages/server/src/queueChats/queue-chats.service.ts
> +    await this.redis.del(`${ChatMessageRedisKey}:${queueId}:${student.id}`);
Yea, because I separated the messages from the metadata.

2025-01-30 03:27 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
> +    if (typeof window !== 'undefined') {
this typeof window shouldn't be necessary since it's a client component?

2025-02-04 19:40 UTC, bhunt02 approved these changes
everything's working now! not having the initial issues I was having before and honestly works really good, glad this feature is being added!

2025-02-05 01:11 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +    }
instead of just printing to console, maybe send a message to the user too. Also setIsLoading(false) should be in finally (or after catch), otherwise it will load forever if there's an error.
```suggestion
      if (questionId) {
        API.queueChats.sendMessage(queueId, questionId, input).then(() => {
          mutateQueueChat()
          setInput('')
        }).catch((e) => {
        message.error(getErrorMessage(e))
        }).finally(() => {
        setIsLoading(false)
        })
      }
```

2025-02-05 01:19 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +                  <Fragment key={index}>
if the messages have an id, it is better to make the key this id.

This would matter if for some reason the messages' indexes were to change order (it would cause react to re-render all of the message components again rather than re-using them)

2025-02-05 01:21 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> +          <>
unused fragment

2025-02-05 01:35 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> +            ? 'fixed bottom-8 z-50 max-h-[90vh] w-screen md:right-1 md:max-w-[400px]'
~~bottom-8 is going to make this appear too high on mobile, probably better to do md:bottom-8 bottom-5~~ Actually I tested it out and bottom-8 looks far too high on pages with a scroll bar. Yes bottom-5 will overlap with the footer a bit, but trust me that's a far better tradeoff then having this button more likely to overlap page content.
![image](https://github.com/user-attachments/assets/080ce994-86c9-437c-9b22-8dfa58453c6e)
![image](https://github.com/user-attachments/assets/c12fb7b6-b1a8-4645-9958-f17220699d81)

Also this was on one of my TODOs, but i'll just add it here since it's easy:

`md:right-1 lg:right-3 xl:right-5 2xl:right-7`

idea being that for larger and larger screens it won't be too far right, but for smaller screens it won't overlap important info as much. If you want to toss this in that would be sweet (it would merge conflict otherwise)

2025-02-05 01:44 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
> +            )}
...and the queue page gets even more bloated and complex 😭 

kidding lol, i think it's just inevitable with a page so complex, but it is kinda comical of how massive it is haha

2025-02-05 01:47 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/layout.tsx
> +        {/* If on the queue page, do not display the chatbot */}
Oh yeah so we already discussed this, but I guess just to state it here, I will probably be revisiting this soon to fit the chatbot in there non-intrusively (I have some ideas). I won't start any work yet in case you're still making some changes, but once you feel ready i'll come and give it a stab

2025-02-05 01:53 UTC, AdamFipke commented on packages/frontend/app/components/ChangeLogModal.tsx
> +      <div className="childrenMarkdownFormatted box-border h-[60vh] w-full overflow-y-auto px-4">
I think it's easier to read if it takes up more of the page
```suggestion
      <div className="childrenMarkdownFormatted box-border h-[75vh] w-full overflow-y-auto px-4">
```

2025-02-07 06:05 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +                  <Fragment key={index}>
Yeah, I agree, but since the messages are temporary, they don't have ids. The good thing is messages can't be deleted (since its temporary anyways) so the order will never change.

2025-02-07 06:30 UTC, patrickma6199 commented on packages/frontend/app/components/ChangeLogModal.tsx
> +      <div className="childrenMarkdownFormatted box-border h-[60vh] w-full overflow-y-auto px-4">
I made this change because this:

![image](https://github.com/user-attachments/assets/a335fe36-7ae1-4805-9af5-d4a3df479b4e)

was how the mobile view looked. I feel like it being somewhat off the center didn't look great.

This is how the mobile view looks with 60vh.

![image](https://github.com/user-attachments/assets/819ebe20-b878-4dd6-8570-dd99c521be4e)

I agree that it looks better being centered in the space below the header bar tho for desktop so ill just add a media query.

2025-02-07 06:35 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> +            ? 'fixed bottom-8 z-50 max-h-[90vh] w-screen md:right-1 md:max-w-[400px]'
You might have some old css cached cause I also moved the button much closer to the side:

![image](https://github.com/user-attachments/assets/658c8435-a1bd-4c15-ae3c-0a40642e9ca3)

2025-02-07 06:35 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
> +          <>
whoopsies

2025-02-07 06:38 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
> +            )}
Yeah, I was actually thinking of refactoring the page slightly just to get the column component defined at the top moved into its own file with its required states. I'm sure there are more changes to be made though to slim it out.

2025-02-07 21:32 UTC, AdamFipke commented on packages/server/src/question/question.controller.ts
> +    private QueueChatService: QueueChatService,
I notice this queuechatservice was added here but it seems to be unused?

2025-02-07 21:54 UTC, AdamFipke commented on packages/server/src/question/question.service.ts
> +      }
```suggestion
      if (isResolving) {
        // Save chat metadata in database (if messages were exchanged)
        await this.queueChatService.endChat(question.queueId, question.id);
      } else if (newStatus in ClosedQuestionStatus) {
        // Don't save chat metadata in database
        await this.queueChatService.clearChat(question.queueId, question.id);
      } else if (isFirstHelped) {
        // Create chat metadata in Redis
        await this.queueChatService.createChat(
          question.queueId,
          question.taHelped,
          question,
        );
      }
```

Hmmm, I realise that there might be a case where a question gets deleted from limbo status or something and it ends up maybe not clearing the chat. So I'm thinking it might be better to just check if newStatus is in ClosedQuestionStatus

2025-02-07 21:58 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats-sse.service.ts
> +        } catch (e) {}
Just curious, so this catch statement pretty much catch any errors and then do nothing with them, would this catch any important errors like redis or http errors?

2025-02-07 22:00 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats-sse.service.ts
> +        } catch (e) {}
Also I see that this limits it to 1 message per second i think? 
Will it throw any errors to the user if they post too quickly?

2025-02-07 22:05 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.controller.ts
> +  @UseGuards(JwtAuthGuard)
```suggestion
```

duplicate guard since the controller already has JwtAuthGuard

2025-02-07 22:07 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.controller.ts
> +      .checkPermissions(queueId, questionId, user.id)
```suggestion
    @UserId() userId: number,
  ) {
    const chatData = await this.queueChatService.getChatData(
      queueId,
      questionId,
    );
    if (!chatData) {
      throw new HttpException(
        ERROR_MESSAGES.queueChatsController.chatNotFound,
        HttpStatus.NOT_FOUND,
      );
    }

    await this.queueChatService
      .checkPermissions(queueId, questionId, userId)
```

2025-02-07 22:14 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.controller.ts
> +      const isStaff = user.id === metadata.staff.id;
```suggestion
    @UserId() userId: number,
    @Body('message') message: string,
  ) {
    const metadata = await this.queueChatService.getChatMetadata(
      queueId,
      questionId,
    );
    if (!metadata) {
      throw new HttpException(
        ERROR_MESSAGES.queueChatsController.chatNotFound,
        HttpStatus.NOT_FOUND,
      );
    }

    const allowedToSend = await this.queueChatService.checkPermissions(
      queueId,
      questionId,
      userId,
    );
    if (!allowedToSend) {
      throw new HttpException(
        ERROR_MESSAGES.queueChatsController.sendNotAuthorized,
        HttpStatus.FORBIDDEN,
      );
    }
    try {
      const isStaff = userId === metadata.staff.id;
```

2025-02-07 22:21 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.controller.ts
> +@UseGuards(JwtAuthGuard)
One thought was to add QueueRolesGuard and add some `Roles` decorators to some of these methods so that only people in the course can call them, but upon looking at your methods more closely that might not be necessary thanks to your .checkPermissions checks so maybe what you have should be good. Maybe one thought is to add a comment about it anyway that these methods don't use any roles guards since they use .checkPermissions

2025-02-07 22:30 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats.service.spec.ts
> +jest.mock('nestjs-redis');
huh neat, i didn't know you could mock whole packages in jest, good to know

2025-02-07 22:53 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +        message={`Chat data is not available.`}
```suggestion
        message={`Chat with ${isStaff ? 'student' : 'TA'} is not available.`}
```

2025-02-07 23:13 UTC, AdamFipke approved these changes
Changes look pretty good! I manually tested the simple case of starting to help someone, sending messages, and finish helping on both desktop and mobile for staff and student.

The suggestions I have for the backend are pretty minor. 

And I guess all that's needed is to re-add the chatbot (will need to see how it looks like on desktop and mobile for staff and student (so 4 cases)), and once that's done it should be good to merge

2025-02-27 21:46 UTC, AdamFipke commented on packages/server/src/queueChats/queue-chats-sse.service.ts
> +        } catch (e) {}
okay well from some testing, it certainly seems like you can spam messages so 🤷‍♂️

2025-02-27 21:52 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx
> +        message={`Chat data is not available.`}
I ended up removing this alert and instead opted to just return an empty fragment if there was an error since the error was kinda large and intrusive, which might get distracting for students if they start getting helped but then just see a big warning message

2025-02-27 21:55 UTC, AdamFipke commented on packages/server/src/question/question.service.ts
> +      }
i am going to implement these changes real quick

2025-02-27 22:00 UTC, AdamFipke commented
ready to merge

2025-03-03 00:24 UTC, merged