Display Unread Async Questions Count
ubco-db/helpme pull request #194
Opened 2024-12-03 20:17 UTC by patrickma6199

# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Closes # 91

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [X] This change requires a database query to update old data on production. (but covered in migration)

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any work that this PR is dependent on has been merged into the main branch
- [ ] Any UI changes have been checked to work on desktop, tablet, and mobile

2025-01-04 01:07 UTC, AdamFipke commented on packages/server/src/course/course.controller.ts
> +  }
instead of making it its own endpoint, have you considered going into profile.controller and change .get so that it also returns the unreadAsyncQuestions? It could save some API calls 

i.e.
```ts
 const courses = user.courses
      ? user.courses
          .filter((userCourse) => userCourse?.course?.enabled)
          .map((userCourse) => {
            return {
              course: {
                id: userCourse.courseId,
                name: userCourse.course.name,
		count: userCourse.unreadAsyncQuestions // add this line
              },
              role: userCourse.role,
            };
          })
      : [];
```

And then to get the undreadAsyncQuestions, you could do something similar to the getRoleInCourse function.

2025-01-04 01:13 UTC, AdamFipke commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
i'm not finished reviewing the code but i'm not sure if you want to leave this nullable, i think you might just want to leave it as a default of 0 with nullable false to ensure that all users have a number for it.

Also maybe you can try using a smaller number type to save some space (probably smallint)

2025-01-04 01:41 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +        }
Huh neat. In my original vision for this, I saw it with some kinda colour (like green or maybe light blue) to grab the user's attention, but I realized how hard it would be to find a good colour for it and I actually am a big fan of what you did here. It's very visually consistent which helps since it's a busy page, but not *too* much so that it's still different enough from the queue cards. 

One small thing though is I think "X Unread Questions" is a little too many characters. Maybe something like "X New Questions" or even just "X New" or "X Unread"

Also, as another thought, maybe we can add a little green (1) indicator or something in the navbar for Anytime Qs

2025-01-04 01:41 UTC, AdamFipke requested changes
see comments

2025-01-04 01:43 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +        }
![image](https://github.com/user-attachments/assets/0b132257-e6df-4226-bf4c-aedd956e48c6)

Oh yeah figured I should show a little screenshot here so if anyone else reviews this they can see what it looks like right now

2025-01-04 19:30 UTC, AdamFipke commented on packages/server/src/asyncQuestion/asyncQuestion.controller.ts
> +        .execute();
Oh right, you might want to add a couple integration tests for async questions for this so that no one accidentally breaks it later

2025-01-07 21:35 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +        }
Yeah, this was my original implementation a couple commits back but I switched it to try out the premade component from ant design. I agree tho that that looks more readable. I'm just wondering whether there's anything we can do maybe color-wise to make it stand out.

2025-01-07 21:39 UTC, patrickma6199 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
Yeah, I just noticed that with many of our table definitions, attributes that shouldn't be nullable and have a default are still nullable, so I tried to follow what seemed to be the standard. Even the ***expires*** column above it's definition has nullable as an attribute despite that having only "true" or "false" is clearly sufficient for this case. I don't think it would do any harm but if you're worried, I can update the entity and migrations.

2025-01-07 21:41 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +        }
Yeah, I'll shorten it so that the bolded numbers of all the cards are slightly more aligned.

2025-01-08 00:48 UTC, AdamFipke commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
yeah there's a bunch of old bad database things that should probably be changed at some point. Like for example, user-course entity has a primary generated column and its courseId and userId are both nullable (meaning optional). This basically means that this user-course entity can exist on it's own when in reality its existence should depend on the user and the course (like if a user or course were to be deleted, the corresponding user-course entity will be deleted, and that any new user-course entities must have a real courseId and userId associated with them). Also I don't think `expires` is even used anymore lol (I think at one point the old khory system had a way to have temporary users and that's what that was for). But yeah it's just like a future maintainability thing so that some future developer doesn't misuse the field and make it null and cause the system to crash because there was a missing null check somewhere lol.

2025-01-21 22:38 UTC, patrickma6199 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
Yeah no, I totally get you. I just think at this stage personally, its too hard to organize all these minute changes with all of the tasks I had hanging from the first term. I think we should instead just create a new urgent issue to refactor ALL of the table definitions we already have (including this one once the merge is done). That way, I can focus on closing these old PRs, and also, we can make one migration that alters all the tables instead of a bunch of migrations for each of the tables separately. I don't know if I'm explaining my thought process that well so let me know if you need more clarity from me haha.

2025-01-21 22:38 UTC, patrickma6199 commented on packages/server/src/asyncQuestion/asyncQuestion.controller.ts
> +        .execute();
Will do, thanks for pointing this out!

2025-01-21 22:51 UTC, patrickma6199 commented on packages/server/src/course/course.controller.ts
> +  }
I thought of this but thought that the response from that endpoint is already really big. Thinking about it now though, this would add hardly anything relative to the response and once I finish the profile caching issue I had, that would fix this fine. I'll refactor it, thanks for bringing it up.

2025-01-21 23:15 UTC, bhunt02 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
> Yeah no, I totally get you. I just think at this stage personally, its too hard to organize all these minute changes with all of the tasks I had hanging from the first term. I think we should instead just create a new urgent issue to refactor ALL of the table definitions we already have (including this one once the merge is done). That way, I can focus on closing these old PRs, and also, we can make one migration that alters all the tables instead of a bunch of migrations for each of the tables separately. I don't know if I'm explaining my thought process that well so let me know if you need more clarity from me haha.

We haven't generally been making migrations regardless since it's set to update the database schema automatically to what is seen in the entities.

2025-01-22 16:27 UTC, patrickma6199 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
Yeah, we should definitely not keep prod that way since rollbacks would be a pain. I'll just generate a new migration file then to avoid issues once/if prod switches out of "development mode".

2025-01-22 17:28 UTC, patrickma6199 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
Which one was the second nullable you wanted me to remove? I don't think we should mess with the primary key acting attributed if they're nullable already since previous devs might have worked around it and I don't want to risk breaking anything. If you meant the expires field, I can remove it from there too.

2025-01-22 18:10 UTC, bhunt02 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
> Which one was the second nullable you wanted me to remove? I don't think we should mess with the primary key acting attributed if they're nullable already since previous devs might have worked around it and I don't want to risk breaking anything. If you meant the expires field, I can remove it from there too.

There's no primary columns that are designated nullable, probably because that's impossible (relational integrity rules)
You can remove 'default' from expires because it has a defined default, but we can check the production database to see if there's any null values that currently exist (though I believe that may also be impossible)

Not sure what the other property listed here is

2025-01-22 18:15 UTC, bhunt02 reviewed
I'm a bit uncomfortable with the implementation (there being no relation joining the async question + user course model with a boolean attribute to indicate if it's read), but I think this could work fine. I only worry that we'll have failed operations, but since it resets to zero rather than decrementing, it's unlikely it'll cause faults in the application.

2025-01-22 19:44 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
this does not need to be in a useEffect since userInfo (and userInfo's count) does not change on this page.

Instead, I would just leave it as the following (not in any hooks)
```
const count = userInfo.courses.find(
        (c) => c.course.id === cid,
      )?.unreadCount
```

If you want, you can use a useMemo to cache the calculation, but seeing as how this is pretty much just a small for loop, doing a useMemo isn't going to improve performance much at all.

2025-01-24 00:34 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/async_centre/page.tsx
> +    API.course.updateUnreadAsyncCount(courseId)
Good I like that there isn't an await here. 

One idea is to add a check so that it doesn't call the endpoint if it's already 0. Also, this should be updating the userInfo context otherwise it won't actually be updating the frontend when they go back to the course page (since userInfo context does not update automatically)

2025-01-24 00:37 UTC, AdamFipke commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
> Which one was the second nullable you wanted me to remove? I don't think we should mess with the primary key acting attributed if they're nullable already since previous devs might have worked around it and I don't want to risk breaking anything. If you meant the expires field, I can remove it from there too.

Ah it was just the one field that needed to be changed for this PR, i think i was getting mixed up with another PR that had some nullable fields that shouldn't be nullable. But yeah looks like you made the change so this PR should be good in that regard

2025-01-24 00:40 UTC, AdamFipke requested changes
Just a couple small frontend comments but other than that should be good

2025-01-24 00:43 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
> this does not need to be in a useEffect since userInfo (and userInfo's count) does not change on this page.
> 
> Instead, I would just leave it as the following (not in any hooks)
> 
> ```
> const unreadCount = userInfo.courses.find(
>         (c) => c.course.id === cid,
>       )?.unreadCount
> ```
> 
> If you want, you can use a useMemo to cache the calculation, but seeing as how this is pretty much just a small for loop, doing a useMemo isn't going to improve performance much at all.

useEffect will update when userInfo changes (never)
Declaring it as a const will cause it to happen on every frame (no caching)
I'd agree with useMemo to cache the value directly (removing the need for setState)

Changing from useEffect to a const will hinder performance (barely) and to useMemo not change performance much at all, the point is mostly that the const has the variable recalculated at each render

2025-01-24 05:17 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
> Declaring it as a const will cause it to happen on every frame (no caching)

Just curious, is it every frame or is it every re-render?

2025-01-27 12:05 UTC, patrickma6199 commented on packages/server/src/profile/user-course.entity.ts
> +  @Column({ nullable: true, default: 0 })
> > Which one was the second nullable you wanted me to remove? I don't think we should mess with the primary key acting attributed if they're nullable already since previous devs might have worked around it and I don't want to risk breaking anything. If you meant the expires field, I can remove it from there too.
> 
> There's no primary columns that are designated nullable, probably because that's impossible (relational integrity rules) You can remove 'default' from expires because it has a defined default, but we can check the production database to see if there's any null values that currently exist (though I believe that may also be impossible)
> 
> edit: Yeah I'd remove the nullable argument on unreadAsyncQuestions since a column with a default field can't be nullable. Since it'll be an alter table statement that adds it to user course model it can fill the existing rows with the default value

I mean the "primary key acting attributes" (with a typo my bad). I am aware that primary keys cannot be nullable but since we have a lot of primary-key-like columns that are not actually primary keys in the database, the backend relies on them as if they were primary keys for relationships so removing them would not be smart.

2025-01-27 12:16 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
> > > Declaring it as a const will cause it to happen on every frame (no caching)
> > 
> > 
> > Just curious, is it every frame or is it every re-render?
> 
> My bad for inconsistent phrasing - there's no 'frame' because it's just a DOM render that will re-render based on flags we set in our code. It's on every re-render, and there's far better places to optimize rerenders - since this useEffect would only execute once it actually lowers the complexity of each re-render since the value is cached in the React State object and doesn't have to be recalculated. Declaring it as a const will make it more complex by adding that additional computation on each render. Either way, it is a negligible effect.
> 
> Basically, the DOM will only ever re-render when a flag in a useCallback, useMemo, useEffect, etc. is altered, when component parameters are altered, or when a State object is altered, as far as I remember. What we should worry about more in optimization of renders is ensuring we aren't doing unnecessary amounts of large data retrieval from API routes, less so simple use[...] structures in pages to make them work.

I'm pretty sure that since it comes from the user context and isn't a calculated value, there's nothing to do when re-renders take place here so a const should be fine.

2025-01-27 12:33 UTC, bhunt02 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
> I'm pretty sure that since it comes from the user context and isn't a calculated value, there's nothing to do when re-renders take place here so a const should be fine.

find() is O(n)

2025-01-27 12:33 UTC, patrickma6199 commented
> I'm a bit uncomfortable with the implementation (there being no relation joining the async question + user course model with a boolean attribute to indicate if it's read), but I think this could work fine. I only worry that we'll have failed operations, but since it resets to zero rather than decrementing, it's unlikely it'll cause faults in the application.

It would be unnecessary here since we would never need to know which questions are being counted, only that there are a given number of unread messages on a per-course per-user basis. It would just add needless join operations to value retrieval. If in the future, we have other relational attributed that might work well being grouped together, then I'd agree with the organizational benefit.

Also, what failed operations? I guess my implementation assumes only one device is logged in so there could be a kind of race condition with incrementing and resetting the value if they happen on two devices. I don't see how decrementing would help here though. When you enter the async centre, you would have "read" all the unread questions presumably. I don't see the benefit of spreading that operation out in terms of preventing failed operations.

2025-01-28 21:15 UTC, bhunt02 approved these changes
Looks good just please fix the tests :)

2025-02-03 03:24 UTC, AdamFipke approved these changes
Looks good!

2025-02-03 03:24 UTC, AdamFipke approved these changes
Looks good!

2025-02-03 03:42 UTC, merged

2025-02-03 09:05 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/async_centre/page.tsx
> +
wait no crap, this doesn't update the userinfo context so it won't actually update until the user refreshes the page

i mentioned this in one of my comments but forgot to double check to make sure the change was made

2025-02-03 09:11 UTC, AdamFipke commented on packages/frontend/app/(dashboard)/course/[cid]/async_centre/page.tsx
> +
pushed a fix on prod, only took a min to do

2025-04-25 22:37 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/components/AsyncCentreCard.tsx
> +  }, [userInfo])
Just saw this and wanted to add, the find() call is indeed in O(n) time but the dependency array will only allow this effect to run when userInfo is changed (never so long as you're the same user you were). In other words, const is fine. Using, for instance, a useMemo() or useCallback() here would just be adding another hook that runs when dependencies change to a hook that runs when dependencies change.

2025-04-25 22:39 UTC, patrickma6199 commented on packages/frontend/app/(dashboard)/course/[cid]/async_centre/page.tsx
> +
Sorry, I just saw this thread. Thanks for this addition on behalf of past Patrick!